esphome:
  name: bedroom-monitor

esp32:
  board: esp32-devkitlipo # Change this to your specific board type if known

# Connect to your WiFi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enables the "over the air" updates
# ota:
#   password: "some_password"

# This enables the web view so you can see the temp in your browser
web_server:
  port: 80

#connection to AWS here
mqtt:
  broker: your-unique-id.iot.us-east-1.amazonaws.com # Find this in AWS IoT Settings
  port: 8883
  client_id: bedroom_esp32
  
  # You will paste the contents of the files you downloaded here
  certificate_authority: |
    -----BEGIN CERTIFICATE-----
    (Paste Root CA 1 here)
    -----END CERTIFICATE-----
  client_certificate: |
    -----BEGIN CERTIFICATE-----
    (Paste Device Certificate here)
    -----END CERTIFICATE-----
  client_private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    (Paste Private Key here)
    -----END RSA PRIVATE KEY-----

sensor:
  - platform: ntc
    sensor: resistance_sensor
    calibration:
      #standard for a 10k thermistor. 
      #if readings way off, can tune these.
      - 10.0kOhm -> 25°C 
    name: "Room Temperature"
    update_interval: 30min

  - platform: resistance
    id: resistance_sensor
    sensor: source_sensor
    configuration: DOWNSTREAM  # This matches the wiring guide above
    resistor: 10kOhm
    reference_voltage: 3.3V

  - platform: adc
    id: source_sensor
    pin: GPIO32         #plug in your wire
    update_interval: 30min

    - platform: statistics
    name: "Nightly Low Temperature"
    type: min
    sensor: "Room Temperature"
    # track lowest temp recorded

    